---
- name: Update systems
  hosts: all
  become: yes
  tasks:
     - name: Install updates for RedHat/CentOS systems
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
