---
- hosts: all

  become: true
  tasks:
     - name: Install updates for RedHat/CentOS systems
       yum:
        name: '*'
        state: latest
       when: ansible_facts['os_family'] == "RedHat"
