---
- name: Update systems
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Install updates for Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"

    - name: Install updates for RedHat/CentOS systems
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install updates for Amazon Linux systems
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "Amazon"
